import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import static org.assertj.core.api.Assertions.assertThat;

class OfferManagementSystemApplicationImplFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalFunctionalIntegrationImplTest {

    @Test
    @DisplayName("should be instantiable")
    void shouldBeInstantiable() {
        assertThat(true).isTrue();
    }
}
